name: create pull request

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: make a change
        run: |
          expr $(cat dummy/test.txt) + 1 >dummy/test.txt

      - name: create pull request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          # token: ${{ secrets.PR_TOKEN }}
          author: 'Nerijus K. <14043736+nerijusk@users.noreply.github.com>'
          committer: 'Nerijus K. <14043736+nerijusk@users.noreply.github.com>'
          body: This is a new pull request
          base: main
          branch: pr-create-test
          title: 'chore(core): automated pull request'

      - name: merge pull request
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr view ${{ steps.create-pr.outputs.pull-request-number }} \
            --json autoMergeRequest,mergeStateStatus,mergeable,number,state,statusCheckRollup,title | jq -r .
          echo "Giving some time for GitHub to start checks on pull request" && sleep 15
          gh pr checks ${{ steps.create-pr.outputs.pull-request-number }} --required --watch --interval 15
          gh pr merge ${{ steps.create-pr.outputs.pull-request-number }} --admin --delete-branch --squash
