name: input test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, ${{ inputs.logLevel }}"
