name: input test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        type: string
  workflow_call:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        type: string
concurrency:
  group: concurrency-lock
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello, ${{ inputs.logLevel }}"
      - name: Exit code test
        continue-on-error: true
        run: exit 1
