name: list var test
on:
  workflow_dispatch:
env:
  PATHS: |
    ^LICENSE
    ^.github/workflows
jobs:
  production-deploy-needed:
    runs-on: ubuntu-latest
    outputs:
      deploy_needed: ${{ steps.check.outputs.deploy_needed }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if deploy is needed
        id: check
        run: bash scripts/prod-deploy-check.sh
  production-deploy:
    needs:
      - production-deploy-needed
    if: needs.production-deploy-needed.outputs.deploy_needed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          set -euo pipefail
          echo "Deploying..."
