name: list var test
on:
  workflow_dispatch:
env:
  PATHS: '["^LICENSE", "^.github/workflows"]'
jobs:
  production-deploy-needed:
    runs-on: ubuntu-latest
    outputs:
      deploy_needed: ${{ steps.check.outputs.deploy_needed }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if deploy is needed
        id: check
        run: |
          set -x
          set -euo pipefail
          PATH_LIST=$(mktemp)
          echo -n "${PATHS}" | jq -r .[] >${PATH_LIST}
          cat ${PATH_LIST}
          PREV_TAG=$(git tag --sort=v:refname | tail -n2 | head -n1)
          LAST_TAG=$(git tag --sort=v:refname | tail -n1)
          echo -e "PREV_TAG: ${PREV_TAG}\nLAST_TAG: ${LAST_TAG}"
          CHANGES_DETECTED=$(git diff --name-only ${PREV_TAG}..${LAST_TAG} | grep -Ef ${PATH_LIST} | wc -l || true)
          if [[ "${CHANGES_DETECTED}" -gt 0 ]]; then
            echo "deploy_needed=true" >> "${GITHUB_OUTPUT}"
          else
            echo "deploy_needed=false" >> "${GITHUB_OUTPUT}"
          fi
          rm -f ${PATH_LIST}
  production:
    needs:
      - production-deploy-needed
    if: ${{ needs.production-deploy-needed.outputs.deploy_needed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          set -x
          set -euo pipefail
          echo "Deploying..."
