name: pr label test
on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - unlabeled
env:
  RUNNER_DEBUG: 0
jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check labels
        id: check
        env:
          PR_LABEL: ${{ toJson(github.event.label) }}
          PR_ACTION: ${{ github.event.action }}
        run: bash scripts/pr-label-check.sh
      - id: label-check
        env:
          PR_LABEL: ${{ toJson(github.event.label) }}
        run: |
          LABEL_NAME=$(echo "${PR_LABEL}" | jq -r .name | sed 's/ //g' | cut -f2 -d:)
          echo "label_name=${LABEL_NAME}" >>${GITHUB_OUTPUT}
      - id: set-matrix-all
        if: ${{ env.label_name == 'all' }}
        run: echo "all"
      - id: set-matrix-specific
        if: ${{ env.label_name != 'all' }}
        run: echo "NOT all"
