name: pr label test
on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - unlabeled
env:
  RUNNER_DEBUG: 0
jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check labels
        id: check
        env:
          PR_LABEL: ${{ toJson(github.event.label) }}
          PR_ACTION: ${{ github.event.action }}
        run: bash scripts/pr-label-check.sh
